### PR TITLE
Add Rijndael-256 cipher and use libsodium's ECC implementation

### PR DESCRIPTION
**Pull request by ldr709**
This changes are needed for implementing [POPF OTs](https://github.com/osu-crypto/libOTe/pull/50).

### CODE REVIEW

**Comment by ladnir** [comment]
Cool! I'll review it soon and accept.

**Comment by ladnir** [comment]
mostly everything looks great. For Rijndael256, can we rename it AES256 so that we are consistent?

**Comment by ldr709** [comment]
AES256 usually refers to 256-bit key size AES, while the cipher I need for POPF OT has a 256-bit block size. 128, 192, and 256-bit settings were given for both key size and block size in the original Rijndael proposal, but only the 128-bit block size versions were adopted as the AES standard, so I thought it would be more appropriate to call it Rijndael256.

**Review by ladnir — APPROVED** [review]
looks good.

**Pull request merged**
